import { library } from "@fortawesome/fontawesome-svg-core";

// Solid weight icons
import {
  faBold,
  faBooks as faBooksSolid,
  faCode,
  faFileAlt as faFileAltSolid,
  faH1,
  faH2,
  faImage,
  faInbox,
  faItalic,
  faLink,
  faListOl,
  faListUl,
  faPlusCircle,
  faQuoteLeft,
  faStar as faStarSolid,
  faStrikethrough,
  faTag as faTagSolid,
  faTerminal,
  faTrashAlt as faTrashAltSolid
} from "@fortawesome/pro-solid-svg-icons";

// Regular weight icons
import {
  faEnvelope,
  faExclamationCircle,
  faGlobe,
  faPhone,
  faSpinner as faSpinnerReg,
  faTimes as faTimesReg
} from "@fortawesome/pro-regular-svg-icons";

// Light weight icons
import {
  faAngleDown,
  faAngleRight,
  faBars,
  faBell,
  faBooks as faBooksLight,
  faChevronLeft,
  faCloudUpload,
  faCogs,
  faComment,
  faDownload,
  faFileAlt as faFileAltLight,
  faPencilAlt,
  faPlus,
  faQuestionCircle,
  faSearch,
  faSignOut,
  faSmile,
  faSpinner as faSpinnerLight,
  faStar as faStarLight,
  faTachometerAlt,
  faTag as faTagLight,
  faTags,
  faTimes as faTimesLight,
  faTimesCircle,
  faTrashAlt as faTrashAltLight,
  faUserCircle
} from "@fortawesome/pro-light-svg-icons";

// Brand icons
import {
  faDribbble,
  faFacebookF,
  faGithub,
  faInstagram,
  faLinkedin,
  faMediumM,
  faSkype,
  faSlackHash,
  faSnapchatGhost,
  faTwitter
} from "@fortawesome/free-brands-svg-icons";

library.add(
  faAngleDown,
  faAngleRight,
  faBars,
  faBell,
  faBold,
  faBooksLight,
  faBooksSolid,
  faChevronLeft,
  faCloudUpload,
  faCode,
  faCogs,
  faComment,
  faDownload,
  faDribbble,
  faEnvelope,
  faExclamationCircle,
  faFacebookF,
  faFileAltLight,
  faFileAltSolid,
  faGithub,
  faGlobe,
  faH1,
  faH2,
  faImage,
  faInbox,
  faInstagram,
  faItalic,
  faLink,
  faLinkedin,
  faListOl,
  faListUl,
  faMediumM,
  faPencilAlt,
  faPhone,
  faPlus,
  faPlusCircle,
  faQuestionCircle,
  faQuoteLeft,
  faSearch,
  faSignOut,
  faSkype,
  faSlackHash,
  faSmile,
  faSnapchatGhost,
  faSpinnerLight,
  faSpinnerReg,
  faStarLight,
  faStarSolid,
  faStrikethrough,
  faTachometerAlt,
  faTagLight,
  faTags,
  faTagSolid,
  faTerminal,
  faTimesCircle,
  faTimesLight,
  faTimesReg,
  faTrashAltLight,
  faTrashAltSolid,
  faTwitter,
  faUserCircle
);
