#!/bin/sh

# script/server: Launch the application.

set -e

cd "$(dirname "$0")/.."

if [ ! -f src/index.css ]; then
  echo "==> Initial build of index.css..."
  npm run build-css
fi

heroku local:run npm start
